import { Matrix4x4, Vec3 } from "../../PrimitiveType";
export declare class Camera extends Matrix4x4 {
    private static _upVector;
    private static _origin;
    static get upVector(): Vec3;
    static get origin(): Vec3;
    protected _screenW: number;
    protected _screenH: number;
    protected _zNear: number;
    protected _zFar: number;
    protected _fovInDegree: number;
    protected _focal: number;
    protected _eyePosition: Vec3;
    protected _target: Vec3;
    protected _viewMatrix: Matrix4x4;
    protected _projectionMatrix: Matrix4x4;
    protected mustUpdateMatrix: boolean;
    constructor(screenW: number, screenH: number, fovInDegree: number, zNear?: number, zFar?: number);
    get focal(): number;
    get eyePosition(): Vec3;
    get target(): Vec3;
    get upVector(): Vec3;
    get viewMatrix(): Matrix4x4;
    get projectionMatrix(): Matrix4x4;
    get screenW(): number;
    set screenW(n: number);
    get screenH(): number;
    set screenH(n: number);
    get fovInDegree(): number;
    set fovInDegree(n: number);
    get zFar(): number;
    set zFar(n: number);
    get zNear(): number;
    set zNear(n: number);
    get x(): number;
    get y(): number;
    get z(): number;
    set x(n: number);
    set y(n: number);
    set z(n: number);
    update(): void;
}
